name: LineageOS Builder
on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'Manifest Branch'
        required: true
        default: 'lineage-20.0'
        type: choice
        options:
          - 'cm-11.0'
          - 'cm-12.1'
          - 'stable/cm-13.0-ZNH0E'
          - 'stable/cm-13.0-ZNH2K'
          - 'stable/cm-13.0-ZNH5Y'
          - 'cm-13.0'
          - 'translations/cm-14.1'
          - 'cm-14.1'
          - 'lineage-15.0'
          - 'staging/lineage-15.1'
          - 'lineage-15.1'
          - 'backups/test/lineage-16.0'
          - 'backups/20181204-0512/lineage-16.0'
          - 'lineage-16.0'
          - 'lineage-17.0'
          - 'lineage-17.1'
          - 'lineage-18.0'
          - 'lineage-18.1'
          - 'lineage-19.0'
          - 'lineage-19.1'
          - 'lineage-20.0'
      DEVICE_TREE_URL:
        description: 'Device Tree URL'
        required: true
        default: 'https://github.com/LineageOS/android_device_oneplus_bacon'
      DEVICE_TREE_BRANCH:
        description: 'Device Tree Branch'
        required: true
        default: 'lineage-18.0'
      BRAND:
        description: 'Brand'
        required: true
        default: 'oneplus'
      DEVICE_CODE:
        description: 'Device Code'
        required: true
        default: 'bacon'
jobs:
  LineageOS:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Free up space
        run: bash sh/ROM/unin.sh

      - name: Set up the Compilation environment
        run: bash sh/ROM/sudo.sh

      - name: Git Config
        run: |
          rm -rf ~/los
          mkdir ~/los
          cd ~/los
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Sync Minimal Manifest
        run: |
          cd ~/los
          repo init --depth=1 -u https://github.com/LineageOS/android.git -b ${{ inputs.MANIFEST_BRANCH }} --git-lfs

      - name: Sync Source
        run: |
          cd ~/los
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
          rm -rf .rep

      - name: Clone Device Tree
        run: |
          cd ~/los
          git clone -b ${{ inputs.DEVICE_TREE_BRANCH }} ${{ inputs.DEVICE_TREE_URL }} device/${{ inputs.BRAND }}/${{ inputs.DEVICE_CODE }}

      - name: Prepare the device-specific code
        run: |
          cd ~/los
          chmod 777 build/envsetup.sh
          source build/envsetup.sh
          breakfast ${{ inputs.DEVICE_CODE }}

      - name: Extract proprietary blobs
        run: |
          cd ~/los/device/${{ inputs.BRAND }}/${{ inputs.DEVICE_CODE }}
          ./extract-files.sh

      - name: Start the build
        run: |
          cd ~/los
          croot
          brunch ${{ inputs.DEVICE_CODE }}

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Custom Recovery for ${{ inputs.DEVICE_CODE }}
          tag_name: LOS
          body: |
            Device: ${{ inputs.DEVICE_CODE }}
            Type: LineageOS
          files: unofficialtwrp-${{ inputs.DEVICE_CODE }}.img
